import type { FileMeta, ToolMeta } from '../../usb';

/**
 * Normalises what a slicer records about a print into one shape, from either
 * source: the INI key/values at the head of a .bgcode container, or the `; key =
 * value` comment block an ASCII .gcode carries. The comment block is richer — it
 * has the exact print time and per-tool filament weight, which in a .bgcode live
 * in a compressed block 350 KB deep.
 *
 * Type-only import, so this stays runtime-dependency-free and unit-testable under
 * the project's bare Vitest config.
 */

/** Slicer lists use `;` between strings and `,` between numbers; accept either. */
function splitList(value: string | undefined): string[] {
	if (!value) return [];
	return value.split(/[;,]/).map((v) => v.trim());
}

function num(value: string | undefined): number | undefined {
	if (value == null || value.trim() === '') return undefined;
	const n = Number(value);
	return Number.isFinite(n) ? n : undefined;
}

/** The bed is a single heater, so its per-filament values collapse to the distinct ones. */
function joinDistinct(values: string[]): string | undefined {
	const seen = [...new Set(values.filter((v) => v !== ''))];
	return seen.length > 0 ? seen.join(', ') : undefined;
}

/** Zips the parallel per-extruder lists into one row per tool. */
function toolsFrom(lists: {
	material?: string;
	nozzle?: string;
	temperature?: string;
	colour?: string;
	grams?: string;
}): ToolMeta[] {
	const material = splitList(lists.material);
	const nozzle = splitList(lists.nozzle);
	const temperature = splitList(lists.temperature);
	const colour = splitList(lists.colour);
	const grams = splitList(lists.grams);

	const count = Math.max(material.length, nozzle.length, temperature.length, colour.length, grams.length);
	const tools: ToolMeta[] = [];
	for (let i = 0; i < count; i++) {
		const tool: ToolMeta = { index: i + 1 };
		if (material[i]) tool.material = material[i];
		if (num(nozzle[i]) != null) tool.nozzleMm = num(nozzle[i]);
		if (num(temperature[i]) != null) tool.nozzleTempC = num(temperature[i]);
		if (/^#[0-9a-f]{3,8}$/i.test(colour[i] ?? '')) tool.colour = colour[i];
		if (num(grams[i]) != null) tool.filamentGrams = num(grams[i]);
		tools.push(tool);
	}
	return tools;
}

/** Builds a FileMeta from the INI values parseBgcodeHeader() returns. */
export function fromBgcodeHeader(kv: Record<string, string>): FileMeta {
	return prune({
		tools: toolsFrom({
			material: kv.filament_type,
			nozzle: kv.nozzle_diameter,
			temperature: kv.temperature,
			colour: kv.extruder_colour
		}),
		layerHeightMm: num(kv.layer_height),
		infill: kv.fill_density || undefined,
		printerModel: kv.printer_model || undefined,
		bedTempC: joinDistinct(splitList(kv.bed_temperature)),
		maxHeightMm: num(kv.max_layer_z),
		producer: kv.Producer || undefined
	});
}

/** `; key = value` comment lines, as PrusaSlicer writes them into an ASCII .gcode. */
export function fromGcodeComments(head: Buffer | string): FileMeta | null {
	const text = typeof head === 'string' ? head : head.toString('latin1');
	const kv: Record<string, string> = {};
	for (const line of text.split(/\r?\n/)) {
		const m = /^;\s*([^=]+?)\s*=\s*(.*)$/.exec(line);
		if (m) kv[m[1].toLowerCase()] = m[2].trim();
	}
	if (Object.keys(kv).length === 0) return null;

	return prune({
		tools: toolsFrom({
			material: kv['filament_type'],
			nozzle: kv['nozzle_diameter'],
			temperature: kv['temperature'],
			colour: kv['extruder_colour'],
			grams: kv['filament used [g]']
		}),
		estimatedTime: kv['estimated printing time (normal mode)'] || undefined,
		layerHeightMm: num(kv['layer_height']),
		infill: kv['fill_density'] || undefined,
		printerModel: kv['printer_model'] || undefined,
		bedTempC: joinDistinct(splitList(kv['bed_temperature'])),
		maxHeightMm: num(kv['max_print_height']),
		producer: kv['generated by'] || undefined
	});
}

/**
 * PrusaSlicer's default output template ends with the print time, e.g.
 * `reference_box_spacer_0.4n_0.3mm_PLA_XL_1h56m.bgcode`. 352 of the 379 files on
 * the real drive carry it, and it is the only cheap source of an estimate for a
 * .bgcode.
 */
export function printTimeFromName(displayName: string): string | undefined {
	const m = /_(?:(\d+)d)?(?:(\d+)h)?(\d+)m\.b?gcode$/i.exec(displayName);
	if (!m) return undefined;
	const [, d, h, min] = m;
	return [d && `${d}d`, h && `${h}h`, `${min}m`].filter(Boolean).join(' ');
}

/** Drops empty optional fields so the UI can render on presence alone. */
function prune(meta: FileMeta): FileMeta {
	const record = meta as unknown as Record<string, unknown>;
	for (const [key, value] of Object.entries(record)) {
		if (value === undefined || value === '') delete record[key];
	}
	return meta;
}

/** True when nothing worth showing came back. */
export function isEmptyMeta(meta: FileMeta): boolean {
	const { tools, ...rest } = meta;
	return tools.length === 0 && Object.keys(rest).length === 0;
}
