import { describe, expect, it } from 'vitest';
import { fromBgcodeHeader, fromGcodeComments, isEmptyMeta, printTimeFromName } from './meta';

/** Lifted verbatim from data/gcode/Shape-Box_0.4n_0.25mm_PLA_XLIS_25m.gcode. */
const GCODE_COMMENTS = [
	'; generated by PrusaSlicer 2.9.6-beta1 on 2026-06-11 at 22:59:17 UTC',
	'G1 X0 Y0',
	'; filament used [g] = 10.58, 0.00, 0.00, 0.00, 0.00',
	'; estimated printing time (normal mode) = 25m 29s',
	'; estimated printing time (silent mode) = 26m 40s',
	'; bed_temperature = 60,80,80,80,80',
	'; filament_type = PLA;PETG;PETG;PETG;PETG',
	'; fill_density = 15%',
	'; layer_height = 0.25',
	'; nozzle_diameter = 0.4,0.4,0.4,0.4,0.4',
	'; printer_model = XL5IS',
	'; temperature = 220,250,250,250,250',
	'; extruder_colour = #FF8000;#DB5182;#3EC0FF;#FF4F4F;#FBEB7D'
].join('\n');

/** The real PrinterMetadata block off the Prusa XL at 10.33.8.124. */
const BGCODE_KV = {
	Producer: 'PrusaSlicer 2.9.0',
	printer_model: 'XL5',
	filament_type: 'PLA;PLA;PLA;PLA;PLA',
	nozzle_diameter: '0.4,0.4,0.4,0.4,0.4',
	temperature: '210,210,210,210,210',
	bed_temperature: '60,60,60,60,60',
	layer_height: '0.3',
	fill_density: '15%',
	extruder_colour: '#FF8000;#DB5182;#3EC0FF;#FF4F4F;#FBEB7D',
	max_layer_z: '11.90'
};

describe('fromGcodeComments', () => {
	const meta = fromGcodeComments(GCODE_COMMENTS)!;

	it('keeps every tool separate rather than collapsing them', () => {
		expect(meta.tools).toHaveLength(5);
		expect(meta.tools.map((t) => t.material)).toEqual(['PLA', 'PETG', 'PETG', 'PETG', 'PETG']);
		expect(meta.tools.map((t) => t.nozzleTempC)).toEqual([220, 250, 250, 250, 250]);
	});

	it('numbers tools from 1 and carries colour and grams', () => {
		expect(meta.tools[0]).toEqual({
			index: 1,
			material: 'PLA',
			nozzleMm: 0.4,
			nozzleTempC: 220,
			colour: '#FF8000',
			filamentGrams: 10.58
		});
		// 0 g marks a tool this print doesn't actually use — kept, not hidden.
		expect(meta.tools[1].filamentGrams).toBe(0);
	});

	it('reads the print-level fields', () => {
		expect(meta.estimatedTime).toBe('25m 29s');
		expect(meta.layerHeightMm).toBe(0.25);
		expect(meta.infill).toBe('15%');
		expect(meta.printerModel).toBe('XL5IS');
	});

	it('joins the distinct bed temperatures, since there is only one bed', () => {
		expect(meta.bedTempC).toBe('60, 80');
	});

	it('returns null when there are no slicer comments at all', () => {
		expect(fromGcodeComments('G1 X0 Y0\nG1 X1 Y1\n')).toBeNull();
	});

	it('handles a single-tool file', () => {
		const single = fromGcodeComments('; filament_type = PLA\n; nozzle_diameter = 0.4\n')!;
		expect(single.tools).toHaveLength(1);
		expect(single.tools[0]).toEqual({ index: 1, material: 'PLA', nozzleMm: 0.4 });
	});
});

describe('fromBgcodeHeader', () => {
	const meta = fromBgcodeHeader(BGCODE_KV);

	it('produces one row per extruder even when they all match', () => {
		expect(meta.tools).toHaveLength(5);
		expect(meta.tools.map((t) => t.colour)).toEqual([
			'#FF8000',
			'#DB5182',
			'#3EC0FF',
			'#FF4F4F',
			'#FBEB7D'
		]);
		expect(new Set(meta.tools.map((t) => t.material))).toEqual(new Set(['PLA']));
	});

	it('reads the print-level fields', () => {
		expect(meta.printerModel).toBe('XL5');
		expect(meta.layerHeightMm).toBe(0.3);
		expect(meta.infill).toBe('15%');
		expect(meta.bedTempC).toBe('60');
		expect(meta.maxHeightMm).toBe(11.9);
		expect(meta.producer).toBe('PrusaSlicer 2.9.0');
	});

	it('has no print time — that block is not in the head', () => {
		expect(meta.estimatedTime).toBeUndefined();
	});

	it('survives an empty header', () => {
		expect(isEmptyMeta(fromBgcodeHeader({}))).toBe(true);
		expect(isEmptyMeta(meta)).toBe(false);
	});
});

describe('printTimeFromName', () => {
	it('reads PrusaSlicer output-template suffixes', () => {
		expect(printTimeFromName('reference_box_spacer_0.4n_0.3mm_PLA_XL_1h56m.bgcode')).toBe('1h 56m');
		expect(printTimeFromName('cilinder_0.4n_0.2mm_PLA_MK3.9S_12m.bgcode')).toBe('12m');
		expect(printTimeFromName('jefes_finales01_0.4n_0.2mm_PLA_XL_1d4h55m.bgcode')).toBe('1d 4h 55m');
		expect(printTimeFromName('Shape-Box_0.4n_0.25mm_PLA_XLIS_25m.gcode')).toBe('25m');
		expect(printTimeFromName('10+10_0.4n_0.2mm_PLA,PLA_XLIS_23h23m.bgcode')).toBe('23h 23m');
	});

	it('gives nothing for a hand-named file rather than guessing', () => {
		expect(printTimeFromName('CABEZAL1_FILAMENTO_CONDUCTOR.bgcode')).toBeUndefined();
		expect(printTimeFromName('benchy.bgcode')).toBeUndefined();
	});
});
