import { describe, expect, it } from 'vitest';
import { extractGcodeThumbnail, sniffImageType } from './thumbnail';

/** Minimal 1x1 PNG, and a JPEG SOI header — enough for the magic-byte check. */
const PNG = Buffer.from(
	'89504e470d0a1a0a0000000d49484452000000010000000108060000001f15c4890000000a49444154789c6300010000050001' +
		'0d0a2db40000000049454e44ae426082',
	'hex'
);
const JPEG = Buffer.from('ffd8ffe000104a46494600010100000100010000ffd9', 'hex');

/** Renders a block the way PrusaSlicer does: base64 across `; `-prefixed lines, 78 chars each. */
function block(marker: string, w: number, h: number, payload: Buffer): string {
	const base64 = payload.toString('base64');
	const lines = base64.match(/.{1,78}/g) ?? [];
	return [
		`; ${marker} begin ${w}x${h} ${base64.length}`,
		...lines.map((l) => `; ${l}`),
		`; ${marker} end`
	].join('\n');
}

const HEADER = '; generated by PrusaSlicer 2.9.6-beta1\n';
const BODY = '\nG1 X0 Y0 E0\nG1 X1 Y1 E1\n';

describe('extractGcodeThumbnail', () => {
	it('returns the PNG block', () => {
		const found = extractGcodeThumbnail(HEADER + block('thumbnail', 380, 285, PNG) + BODY);
		expect(found).not.toBeNull();
		expect(found?.contentType).toBe('image/png');
		expect(found?.width).toBe(380);
		expect(found?.height).toBe(285);
		expect(found?.data.equals(PNG)).toBe(true);
	});

	it('skips QOI blocks and still finds the PNG that follows them', () => {
		const qoi = Buffer.concat([Buffer.from('qoif'), Buffer.alloc(60, 7)]);
		const source =
			HEADER +
			block('thumbnail_QOI', 16, 16, qoi) +
			'\n' +
			block('thumbnail_QOI', 480, 240, qoi) +
			'\n' +
			block('thumbnail', 380, 285, PNG) +
			BODY;

		const found = extractGcodeThumbnail(source);
		expect(found?.contentType).toBe('image/png');
		// The 480x240 QOI is larger, but unsupported — it must not win.
		expect(found?.width).toBe(380);
	});

	it('picks the largest supported block when several are present', () => {
		const source =
			HEADER +
			block('thumbnail', 16, 16, PNG) +
			'\n' +
			block('thumbnail_JPG', 640, 480, JPEG) +
			'\n' +
			block('thumbnail', 100, 100, PNG) +
			BODY;

		const found = extractGcodeThumbnail(source);
		expect(found?.contentType).toBe('image/jpeg');
		expect(found?.width).toBe(640);
	});

	it('returns null when there is no thumbnail', () => {
		expect(extractGcodeThumbnail(HEADER + BODY)).toBeNull();
	});

	it('rejects a block truncated before its end marker', () => {
		const truncated = block('thumbnail', 380, 285, PNG).split('\n').slice(0, -2).join('\n');
		expect(extractGcodeThumbnail(HEADER + truncated + BODY)).toBeNull();
	});

	it('rejects a block whose payload does not match the declared length', () => {
		const tampered = block('thumbnail', 380, 285, PNG).replace(/begin 380x285 \d+/, 'begin 380x285 9999');
		expect(extractGcodeThumbnail(HEADER + tampered + BODY)).toBeNull();
	});

	it('rejects a block whose payload is not really an image', () => {
		const notAnImage = block('thumbnail', 380, 285, Buffer.from('this is not a png at all'));
		expect(extractGcodeThumbnail(HEADER + notAnImage + BODY)).toBeNull();
	});

	it('accepts a Buffer read straight off disk', () => {
		const source = Buffer.from(HEADER + block('thumbnail', 380, 285, PNG) + BODY, 'latin1');
		expect(extractGcodeThumbnail(source)?.data.equals(PNG)).toBe(true);
	});
});

describe('sniffImageType', () => {
	it('recognises the formats we cache', () => {
		expect(sniffImageType(PNG)).toBe('image/png');
		expect(sniffImageType(JPEG)).toBe('image/jpeg');
	});

	it('rejects anything else, so a truncated or bogus cache entry is not served', () => {
		expect(sniffImageType(Buffer.from('qoif' + '\0'.repeat(60)))).toBeNull();
		expect(sniffImageType(Buffer.from('404: Not Found'))).toBeNull();
		expect(sniffImageType(Buffer.alloc(0))).toBeNull();
	});
});
